# Generated by Django 2.2.3 on 2019-07-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190723_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Resturant',
        ),
    ]
